### PR TITLE
Bugfix on Array map

### PR DESCRIPTION
**Pull request by enzoqtvf**
Hello, thanks for your work on this library, I started to use it and it's pretty cool !

I found a bug that I fixed in this PR, not sure how you would like to handle the versionning etc.. so it's up to you :D
 
- Handles optionnal aray map when not given in paramaters
- Handles array map changeset when some nested map are invalid

Also I think we can improve the errors in the main changeset when there is an issue to have something like `[list_maps: ["contains error changeset"]`because right now errors are nested

### CODE REVIEW

**Comment by enzoqtvf** [comment]
@martinthenth Not sure you got the notification, so sending it to you here as well :)

**Comment by martinthenth** [comment]
Hi @enzoqtvf! Thanks for your PR! So I checked out your code and I reproduced nr 1 ("Handles optional array of maps when not given in the paramaters"). The test correctly tests for this case, so we can get that merged soon

I couldn't reproduce nr 2 from the second test. Without the proposed change I get the correct result, i.e. a `valid?: false` changeset when the first map in the list is invalid and the second is valid

Re: Versioning, we can get the change out fast but I want to test it first so 1 or 2 days after merging 🙂

**Comment by martinthenth** [comment]
Hi @enzoqtvf! Could you split up your PR into the first issue and the second? I'd like to merge the first issue and release a new version

**Comment by martinthenth** [comment]
Fixed in https://github.com/martinthenth/goal/pull/50

**Pull request closed without merging**
